siteproger/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	path('',views.index, name = 'index'),
	path('<int:article_id>/',views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment',views.leave_comment, name = 'leave_comment'),

	#path('test/',views.test, name = 'test')
]

siteproger/apps/title/urls.py
from django.urls import path

from . import views

app_name = 'title'
urlpatterns = [
	path('',views.index, name = 'index'),
	# path('<int:article_id>/',views.detail, name = 'detail'),
	# path('<int:article_id>/leave_comment',views.leave_comment, name = 'leave_comment'),

	#path('test/',views.test, name = 'test')
]

siteproger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('title.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

siteproger/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
	article_title = models.CharField('Название статьи', max_length = 200 )
	article_text = models.TextField('Текст статьи')
	pub_date = models.DateTimeField('Дата Публикации')

	def __str__(self):
		return self.article_title

	def was_publishid_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('Имя автора', max_length=50)
	comment_text = models.CharField('Текст коментария', max_length=200)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

siteproger/apps/title/models.py
from django.db import models

# Create your models here.

siteproger/apps/articles/views.py
# from django.http import HttpResponse

# def index(request):
# 	return HttpResponse('Привет, мир!')

# def test(request):
# 	return HttpResponse('это тестовая страница')

from django.shortcuts import render
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect

from django.urls import reverse

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request,'articles/list.html', {'latest_articles_list':latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id)
	except:
		raise Http404("Статья не найдена")

	latest_comments_list = a.comment_set.order_by('-id')[:10]

	return render(request, 'articles/detail.html', {'article': a,'latest_comments_list':latest_comments_list})

def leave_comment(request,article_id):
	try:
		a = Article.objects.get( id = article_id)
	except:
		raise Http404("Статья не найдена")

	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

siteproger/apps/title/views.py
from django.shortcuts import render
# from .models import Article, Comment
from django.http import Http404, HttpResponse

from django.urls import reverse

def index(request):
	# latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	# return render(request,'articles/list.html', {'latest_articles_list':latest_articles_list})
	return render(request,'title/resume.html', {})

siteproger/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} {{article.article_title}}{% endblock %}

{% block content %}

	<h2>{{article.article_title}}</h2>
	<p>{{article.article_text}}</p>
	<em>{{article.pub_date}}</em>

	<hr>
	{% if latest_comments_list %}
		{% for c in latest_comments_list %}
			<p><strong>{{c.author_name}}</strong></p></br>
			<p>{{c.comment_text}}</p><br>
			<br>
		{% endfor %}
	{% else %}
		нет комментариев
	{% endif %}
	<hr>

	<form method="POST" action=" {% url 'articles:leave_comment' article.id %} ">
		{% csrf_token %}
		<input type="text" required placeholder="Name" name="name">
		</br>
		<textarea type="text" required placeholder="Text" cols="30" rows="10" name="text"></textarea>
		</br>
		<button type="submit">Оставить комментарий</button>
	</form>

{% endblock %}

siteproger/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Последнии статьи {% endblock %}

{% block content %}

	{% if latest_articles_list %}
		{% for a in latest_articles_list %}
			<a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></br>
		{% endfor %}
	{% else %}
		нет статей
	{% endif %}

{% endblock %}

siteproger/templates/base.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Egor Kukolschikov">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Кукольщиков Е А</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/starter-template/">

    

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- my styles for this template -->
    <link href='/static/css/style.css' rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="/static/css/starter-template.css" rel="stylesheet">

    <!-- Скрипт для вывода колонок -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>


  </head>
  <body>
	{% block content %}{% endblock %}
</body>
</html>